MOISTURE_ADC_PIN = 35
MOISTURE_DRY_MAX=1200
MOISTURE_WET_MAX=2900
MOISTURE_ADC_WIDTH="ADC.WIDTH_12BIT"
MOISTURE_ADC_ATTEN="ADC.ATTN_11DB"

MQTT_TOPIC = "moisture"
MQTT_WETNESS_TOPIC = MQTT_TOPIC + "/wetness"
