SDA_PIN=10
SCL_PIN=9

WIFI_SSID="meowphone"
WIFI_PASSWORD="labricecat"

MQTT_USER="htl"
MQTT_BROKER="sc.htl-kaindorf.at"
MQTT_PORT=1883
MQTT_PASSWORD="welc0m3"

TOPIC_LOCATION="top"
TOF="tof"
MOISTURE="mois"

MOISTURE_ADC_PIN=1
MOISTURE_DRY_MAX=500
MOISTURE_WET_MAX=1000

SOLENOID=0 #is 0 fr